"""Pull every tier's results into one table.

Run after the training scripts and bench.py. Writes results/SUMMARY.md, which is
the table that goes into the final report.
"""
from __future__ import annotations

import json
from pathlib import Path

RESULTS = Path(__file__).resolve().parents[2] / "results"   # baselines -> src -> repository root


def load(pattern: str) -> dict:
    """Every result JSON matching the pattern, keyed by its tier name."""
    out = {}
    for path in sorted(RESULTS.glob(pattern)):
        data = json.loads(path.read_text())
        out[data["tier"]] = data
    return out


def main() -> None:
    train = load("[0-9]*.json")
    bench = {k.replace("bench_", ""): v for k, v in load("bench_*.json").items()}

    lines = ["# Every model on the test set", "",
             "Generated by `src/baselines/report.py` from the JSON files in this folder. Every row is the",
             "deduplicated test set of 4,750 tickets. The curated version, with the story behind each row,",
             "is the Results table in the top-level README.", "",
             "## Accuracy against size", "",
             "| Tier | Model | Params (M) | Accuracy | Macro-F1 | Train time |",
             "| --- | --- | --- | --- | --- | --- |"]

    def train_minutes(d):
        # older tiers recorded seconds, the final routers record minutes, zero-shot tiers neither
        if "train_seconds" in d:
            return f"{d['train_seconds'] / 60:.1f} min"
        if "train_minutes" in d:
            return f"{d['train_minutes']:.1f} min"
        model = d.get("model", "")
        return "none, not trained" if ("zero-shot" in model or "few-shot" in model) else "not recorded"

    def tier_key(name):
        head = name.split("_")[0]
        num = "".join(c for c in head if c.isdigit())
        return (int(num) if num else 99, head)

    for tier, d in sorted(train.items(), key=lambda kv: tier_key(kv[0])):
        if "accuracy" not in d or "macro_f1" not in d:
            continue
        lines.append(
            f"| {tier.split('_')[0]} | {d.get('model', tier)} | {d.get('params_millions', d.get('params_m', '-'))} | "
            f"{d['accuracy']*100:.1f}% | {d['macro_f1']:.3f} | {train_minutes(d)} |"
        )

    lines += ["", "A 0.0% row is a run whose answers could not be parsed into a queue name (the small Qwen3",
              "model ignored the answer format), see docs/SLM_EXPERIMENT.md. Tier 6 rows are checkpoints of",
              "the same LoRA fine-tune."]

    if bench:
        lines += ["", "## Cost to serve one ticket", "",
                  "| Tier | Disk (MB) | RAM held (MB) | p50 at 1 thread | p50 at 2 threads | p95 at 2 threads |",
                  "| --- | --- | --- | --- | --- | --- |"]
        for tier, d in sorted(bench.items()):
            lat = d["latency"]
            one = lat.get("1_thread", {})
            two = lat.get("2_thread", one)
            lines.append(
                f"| {tier.split('_')[0]} | {d['disk_mb']:.0f} | {d['rss_after_load_mb']:.0f} | "
                f"{one.get('p50_ms','-')} ms | {two.get('p50_ms','-')} ms | {two.get('p95_ms','-')} ms |"
            )

    lines += ["", "## Confidence threshold", "",
              "How much of the queue each model can route on its own, and how often it is right.", "",
              "| Tier | Threshold | Auto-routed | Accuracy when auto-routed | Sent to a person |",
              "| --- | --- | --- | --- | --- |"]
    for tier, d in sorted(train.items(), key=lambda kv: tier_key(kv[0])):
        for row in d.get("thresholds", []):
            if row["threshold"] in (0.0, 0.5, 0.7, 0.9):
                acc = row["accuracy_on_routed"]
                lines.append(
                    f"| {tier.split('_')[0]} | {row['threshold']:.2f} | {row['coverage']*100:.1f}% | "
                    f"{acc*100:.1f}% | {row['sent_to_human']*100:.1f}% |" if acc else ""
                )

    out = RESULTS / "SUMMARY.md"
    out.write_text("\n".join(l for l in lines if l is not None))
    print("\n".join(lines))
    print(f"\nwrote {out}")


if __name__ == "__main__":
    main()
